#https://gitlab.com/lsit-ken3239/live-demo
spring:
  security:
    oauth2:
      client:
        registration:
          gitlab:
            client-id: 31c1aa88d9faab0cf344df7a75c1e4ff8f7bd2d7f7089cabaf1044ed9548a8e5
            client-secret: gloas-89ab8b6549368ff7b6dab500ec858dbc29878261ae3312ba5dfa1f5a71f62365
            scope: openid+profile+email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/gitlab
        provider:
          gitlab:
            issuer-uri: https://gitlab.com
            user-name-attribute: sub


#application  id: 31c1aa88d9faab0cf344df7a75c1e4ff8f7bd2d7f7089cabaf1044ed9548a8e5
#secret : gloas-89ab8b6549368ff7b6dab500ec858dbc29878261ae3312ba5dfa1f5a71f62365